!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! PARAMETERS: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
double precision, parameter:: Rgas = 8.314 !(J/K/mol)  ideal gas constant                              !!
double precision:: Ea_rp, T0_rp, Ea, T0, krp, h0, ke, a, b, Kwest, kw, sigma                           !!
double precision, dimension(6):: CaMg_rock                                                             !!
common /param/ Ea_rp, T0_rp, Ea, T0, krp, h0, ke, a, b, Kwest, kw, sigma, CaMg_rock                    !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
